# Generated by Django 4.1.6 on 2023-03-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(default='../static/img/logovlinder.jpg', upload_to=''),
        ),
    ]
