# Generated by Django 4.1.6 on 2023-03-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, default='../../static/img/logovlinder.jpg', null=True, upload_to=''),
        ),
    ]
