# Generated by Django 4.1.6 on 2023-03-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_producto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, default='../../static/img/logovlinder.jpg', null=True, upload_to='img-producto'),
        ),
    ]
